class DataForestProject:
    def __init__(self,dictionary={}):
        """Constructor"""
        for key in dictionary:
            setattr(self,key,dictionary[key])
    
    data_validation = {
        "type": "object",
        "properties":{
            "property_type":{
                "type":"string"
            },
            "legal":{
                "type":"boolean"
            },
            "conflict":{
                "type":"boolean"
            },
            "past_cultivate":{
                "type":"boolean"
            },
            "natural_disaster":{
                "type":"boolean"
            },
            "pasture":{
                "type":"boolean"
            },
            "agricultural_pasture":{
                "type":"boolean"
            },
            "address":{
                "type":"object",
                "properties":{
                    "state":{
                        "type":"string"
                    },
                    "country":{
                        "type":"string"
                    },
                    "neighborhood":{
                        "type":"string"
                    },
                    "zip":{
                        "type":"string"
                    },
                    "coords":{
                        "type":"number"
                    }
                }
            },
            "shapefile":{
                "type":"boolean"
            },
            "vegetation":{
                "type":"boolean"
            },
            "tree_percentage":{
                "type":"number"
            },
            "land_use":{
                "type":"string"
            },
            "disuse_months":{
                "type":"integer"
            },
            "aprovved":{
                "type":"boolean"
            },
            "project_type":{
                "type":"string"
            },
            "tree_species":{
                "type":"array",
                "items":{
                    "type":"string"
                }
            },
            "months_to_start":{
                "type":"integer"
            },
            "past_project":{
                "type":"boolean"
            }
                
        },
        "required":[
            "project_type",
            "property_type",
            "address"
        ]
    }